# Copyright (c) Gilljan 2020-2026. All rights reserved.
# GWorld v2

#General
Prefix: '&eGWorld &8â”ƒ&7' #prefix of the plugin
Language: 'EN' #avaiable languages: german (de), english (en)
MainWorld: 'world' #while deleting a world the players which are on the world will be teleported to this world

#Update-Notifications
UpdateNotification: true

#AutoImporter
AutoImport: true #deactivate to stop import of maps provided by other systems

#Storage
Storage:
  Type: 'YAML' #avaiable types: YAML, MYSQL
  Host: 'localhost'
  Username: 'root'
  Password: ''
  Database: 'gworld'
  Port: 3306